'use client';

import Image from 'next/image';
import { ChangeEvent, FormEvent, useEffect, useRef, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { Button } from '@astryxdesign/core/Button';
import { Card } from '@astryxdesign/core/Card';
import { Heading } from '@astryxdesign/core/Heading';
import { Text } from '@astryxdesign/core/Text';
import { VStack } from '@astryxdesign/core/VStack';
import { getCustomerToken } from '../../../../../lib/auth';
import RichTextEditor from './RichTextEditor';

type Option = { id:number; code?:number|string; name:string; icon?:string|null };
type Entitlement = { balance:number; posting_fee:number; test_posting_credits:number };
const inputClass='w-full rounded-lg border border-zinc-300 bg-transparent px-3 py-2 outline-none focus:border-zinc-500';

function unwrap(payload: unknown): Option[] {
    const value=payload as {data?:Option[]|{data?:Option[]}};
    return Array.isArray(value?.data)?value.data:(value?.data?.data??[]);
}

export default function CreatePropertyPage(){
 const {locale='vi'}=useParams<{locale:string}>();const router=useRouter();
 const [types,setTypes]=useState<Option[]>([]);const [amenities,setAmenities]=useState<Option[]>([]);const [provinces,setProvinces]=useState<Option[]>([]);const [wards,setWards]=useState<Option[]>([]);
 const [provinceCode,setProvinceCode]=useState('');const [listingType,setListingType]=useState<'sale'|'rent'>('sale');
 const [accessAllowed,setAccessAllowed]=useState(false);const [entitlement,setEntitlement]=useState<Entitlement|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const [featuredPreview,setFeaturedPreview]=useState('');const [galleryPreviews,setGalleryPreviews]=useState<string[]>([]);const urlsRef=useRef<string[]>([]);

 useEffect(()=>{void Promise.all([fetch('/api/search-options?type=property-types'),fetch('/api/search-options?type=amenities'),fetch('/api/search-options?type=provinces')]).then(async([a,b,c])=>{setTypes(unwrap(await a.json()));setAmenities(unwrap(await b.json()));setProvinces(unwrap(await c.json()))})},[]);
 useEffect(()=>{if(!provinceCode)return;void fetch(`/api/search-options?type=wards&province_code=${encodeURIComponent(provinceCode)}`).then(r=>r.json()).then(result=>setWards(unwrap(result)))},[provinceCode]);
 useEffect(()=>()=>urlsRef.current.forEach(url=>URL.revokeObjectURL(url)),[]);
 useEffect(()=>{const timer=setTimeout(async()=>{const token=getCustomerToken();if(!token){router.replace(`/${locale}/customer/login?redirect=${encodeURIComponent(`/${locale}/owner/properties/create`)}`);return}try{const headers={Authorization:`Bearer ${token}`};const walletResponse=await fetch('/api/wallet',{headers,cache:'no-store'});const wallet=await walletResponse.json();const info:Entitlement=wallet.data;if(walletResponse.ok&&(info?.test_posting_credits??0)>0){setEntitlement(info);setAccessAllowed(true);return}const[verificationResponse,ownerResponse]=await Promise.all([fetch('/api/identity-verification',{headers,cache:'no-store'}),fetch('/api/owner-application',{headers,cache:'no-store'})]);const verification=await verificationResponse.json();const owner=await ownerResponse.json();if(!verificationResponse.ok||verification.data?.status!=='approved'){router.replace(`/${locale}/customer/verify-identity?redirect=${encodeURIComponent(`/${locale}/owner/register`)}`);return}if(!ownerResponse.ok||owner.data?.status!=='approved'){router.replace(`/${locale}/owner/register`);return}const eligible=(info?.balance??0)>=(info?.posting_fee??Number.MAX_SAFE_INTEGER);if(!walletResponse.ok||!eligible){router.replace(`/${locale}/wallet`);return}setEntitlement(info);setAccessAllowed(true)}catch{router.replace(`/${locale}/wallet`)}},0);return()=>clearTimeout(timer)},[locale,router]);

 function previewFeatured(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file){setFeaturedPreview('');return}const url=URL.createObjectURL(file);urlsRef.current.push(url);setFeaturedPreview(url)}
 function previewGallery(event:ChangeEvent<HTMLInputElement>){const files=Array.from(event.target.files??[]);const urls=files.map(file=>URL.createObjectURL(file));urlsRef.current.push(...urls);setGalleryPreviews(urls)}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const token=getCustomerToken();if(!token)return;const body=new FormData(event.currentTarget);const description=String(body.get('description')??'').replace(/<[^>]*>/g,'').trim();if(description.length<30){setMessage('Mô tả chi tiết cần có ít nhất 30 ký tự.');return}setBusy(true);setMessage('');try{const response=await fetch('/api/owner/properties',{method:'POST',headers:{Authorization:`Bearer ${token}`},body});const result=await response.json();if(response.ok){router.replace(`/${locale}`);router.refresh()}else setMessage(result.error??result.message??'Không thể đăng tin.')}catch{setMessage('Không thể đăng tin.')}finally{setBusy(false)}}

 if(!accessAllowed)return <main className="mx-auto w-full max-w-5xl px-4 py-10"><Card variant="muted" padding={5}><Text>Đang kiểm tra điều kiện đăng tin...</Text></Card></main>;
 const province=provinces.find(item=>String(item.code??item.id)===provinceCode);

 return <main className="mx-auto w-full max-w-5xl px-4 py-10"><VStack gap={4}>
  <VStack gap={1}><Heading level={2}>Đăng tin bất động sản</Heading><Text type="supporting">Cung cấp thông tin chính xác giúp tin được duyệt nhanh và tiếp cận khách hàng tốt hơn.</Text></VStack>
  <form onSubmit={submit} className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_18rem]">
   <div className="grid gap-4">
    <Card variant="default" padding={5}><VStack gap={3}><Heading level={3}>1. Thông tin cơ bản</Heading><div className="grid gap-3 md:grid-cols-2"><label className="grid gap-1"><Text>Hình thức *</Text><select name="listing_type" value={listingType} onChange={e=>setListingType(e.target.value as 'sale'|'rent')} className={inputClass} required><option value="sale">Bán</option><option value="rent">Cho thuê</option></select></label><label className="grid gap-1"><Text>Loại bất động sản *</Text><select name="property_type_id" className={inputClass} required defaultValue=""><option value="" disabled>Chọn loại</option>{types.map(type=><option key={type.id} value={type.id}>{type.name}</option>)}</select></label><label className="grid gap-1 md:col-span-2"><Text>Tiêu đề tin *</Text><input name="title" className={inputClass} required minLength={10} maxLength={255} placeholder="Ví dụ: Căn hộ 2 phòng ngủ gần trung tâm"/></label></div></VStack></Card>
    <Card variant="default" padding={5}><VStack gap={3}><Heading level={3}>2. Vị trí</Heading><div className="grid gap-3 md:grid-cols-2"><label className="grid gap-1"><Text>Tỉnh/Thành phố</Text><select value={provinceCode} onChange={e=>setProvinceCode(e.target.value)} className={inputClass}><option value="">Chọn tỉnh/thành</option>{provinces.map(item=><option key={item.id} value={String(item.code??item.id)}>{item.name}</option>)}</select></label><label className="grid gap-1"><Text>Phường/Xã</Text><select name="ward" className={inputClass} disabled={!provinceCode} defaultValue=""><option value="">Chọn phường/xã</option>{wards.map(item=><option key={item.id} value={item.name}>{item.name}</option>)}</select></label><input type="hidden" name="city" value={province?.name??''}/><input type="hidden" name="district" value=""/><label className="grid gap-1 md:col-span-2"><Text>Địa chỉ</Text><input name="address" className={inputClass} placeholder="Tên đường, khu vực"/></label><label className="grid gap-1 md:col-span-2"><Text>Địa chỉ chi tiết</Text><input name="address_detail" className={inputClass} placeholder="Số nhà, tòa nhà, số căn..."/></label></div></VStack></Card>
    <Card variant="default" padding={5}><VStack gap={3}><Heading level={3}>3. Giá và đặc điểm</Heading><div className="grid gap-3 md:grid-cols-3"><label className="grid gap-1 md:col-span-2"><Text>Giá *</Text><input name="price" type="number" min="0" step="1000" className={inputClass} required placeholder="Nhập giá"/></label><label className="grid gap-1"><Text>Đơn vị giá</Text><select name="price_unit" className={inputClass} defaultValue={listingType==='rent'?'month':'total'} key={listingType}>{listingType==='sale'?<><option value="total">Tổng giá</option><option value="m2">Theo m²</option></>:<><option value="month">Tháng</option><option value="day">Ngày</option><option value="night">Đêm</option></>}</select></label><label className="grid gap-1"><Text>Diện tích (m²) *</Text><input name="area" type="number" min="1" step="0.01" className={inputClass} required/></label><label className="grid gap-1"><Text>Phòng ngủ</Text><input name="bedrooms" type="number" min="0" className={inputClass}/></label><label className="grid gap-1"><Text>Phòng tắm</Text><input name="bathrooms" type="number" min="0" className={inputClass}/></label><label className="grid gap-1"><Text>Tầng</Text><input name="floor" type="number" min="0" className={inputClass}/></label><label className="grid gap-1 md:col-span-2"><Text>Thông tin pháp lý</Text><input name="legal_info" className={inputClass} placeholder="Sổ đỏ, sổ hồng, hợp đồng..."/></label></div></VStack></Card>
    {listingType==='rent'?<Card variant="default" padding={5}><VStack gap={3}><Heading level={3}>Chính sách thuê dài hạn và đặt cọc</Heading><Text type="supporting">Để trống nếu không có mức giá ưu đãi hoặc không yêu cầu đặt cọc.</Text><div className="grid gap-3 md:grid-cols-3"><label className="grid gap-1"><Text>Ưu đãi từ số tháng</Text><input name="long_term_months" type="number" min="2" max="120" className={inputClass} placeholder="Ví dụ: 6"/></label><label className="grid gap-1"><Text>Giá ưu đãi mỗi tháng</Text><input name="long_term_price" type="number" min="0" step="1000" className={inputClass} placeholder="Giá/tháng"/></label><label className="grid gap-1"><Text>Tiền đặt cọc</Text><input name="deposit_amount" type="number" min="0" step="1000" className={inputClass} placeholder="Không bắt buộc"/></label></div></VStack></Card>:null}
    <Card variant="default" padding={5}><VStack gap={3}><Heading level={3}>4. Tiện ích</Heading>{amenities.length?<div className="grid gap-2 sm:grid-cols-2 md:grid-cols-3">{amenities.map(item=><label key={item.id} className="flex items-center gap-2 rounded-lg border p-3"><input type="checkbox" name="amenities[]" value={item.id}/><span>{item.icon?`${item.icon} `:''}{item.name}</span></label>)}</div>:<Text type="supporting">Chưa có tiện ích để lựa chọn.</Text>}</VStack></Card>
    <Card variant="default" padding={5}><VStack gap={3}><Heading level={3}>5. Mô tả và hình ảnh</Heading><label className="grid gap-1"><Text>Mô tả chi tiết *</Text><RichTextEditor/></label><label className="grid gap-1"><Text>Ảnh đại diện *</Text><input name="featured_image" type="file" accept="image/jpeg,image/png,image/webp" className={inputClass} required onChange={previewFeatured}/></label>{featuredPreview?<Image src={featuredPreview} alt="Ảnh đại diện xem trước" width={900} height={420} unoptimized className="h-64 w-full rounded-xl object-cover"/>:null}<label className="grid gap-1"><Text>Thư viện ảnh (tối đa 10 ảnh)</Text><input name="images[]" type="file" multiple accept="image/jpeg,image/png,image/webp" className={inputClass} onChange={previewGallery}/></label>{galleryPreviews.length?<div className="grid grid-cols-2 gap-2 md:grid-cols-4">{galleryPreviews.slice(0,10).map((url,index)=><Image key={url} src={url} alt={`Ảnh ${index+1}`} width={240} height={160} unoptimized className="h-32 w-full rounded-lg object-cover"/>)}</div>:null}</VStack></Card>
   </div>
   <aside className="lg:sticky lg:top-20 lg:self-start"><Card variant="muted" padding={4}><VStack gap={3}><Heading level={4}>Tóm tắt đăng tin</Heading>{(entitlement?.test_posting_credits??0)>0?<Text>Bạn còn <strong>{entitlement?.test_posting_credits}</strong> lượt đăng tin kiểm thử. Lần này không trừ tiền.</Text>:<Text>Phí đăng tin: <strong>{(entitlement?.posting_fee??0).toLocaleString('vi-VN')} ₫</strong></Text>}<Text type="supporting">Tin sẽ ở trạng thái chờ duyệt và chỉ hiển thị sau khi quản trị viên phê duyệt.</Text><Button type="submit" variant="primary" label="Gửi tin chờ duyệt" isLoading={busy}/>{message?<Text>{message}</Text>:null}</VStack></Card></aside>
  </form>
 </VStack></main>;
}
