'use client';
import {FormEvent,useEffect,useState} from 'react';
import {useParams,useRouter,useSearchParams} from 'next/navigation';
import {Button} from '@astryxdesign/core/Button';import {Card} from '@astryxdesign/core/Card';import {Heading} from '@astryxdesign/core/Heading';import {Text} from '@astryxdesign/core/Text';import {VStack} from '@astryxdesign/core/VStack';import {getCustomerToken} from '../../../../lib/auth';
type Status='unsubmitted'|'pending'|'approved'|'rejected';
export default function VerifyIdentityPage(){const{locale='vi'}=useParams<{locale:string}>();const vi=locale==='vi';const router=useRouter();const search=useSearchParams();const[status,setStatus]=useState<Status>('unsubmitted');const[reason,setReason]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
useEffect(()=>{const timer=setTimeout(async()=>{const token=getCustomerToken();if(!token){router.replace(`/${locale}/customer/login?redirect=${encodeURIComponent(location.pathname+location.search)}`);return}const response=await fetch('/api/identity-verification',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const result=await response.json();if(response.ok){setStatus(result.data?.status??'unsubmitted');setReason(result.data?.rejection_reason??'');if(result.data?.status==='approved'&&search.get('redirect'))router.replace(search.get('redirect')!)}} ,0);return()=>clearTimeout(timer)},[locale,router,search]);
async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const token=getCustomerToken();if(!token)return;setBusy(true);setMessage('');const data=new FormData(event.currentTarget);data.set('verification_type','individual');try{const response=await fetch('/api/identity-verification',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:data});const result=await response.json();if(response.ok){setStatus('pending');setMessage(vi?'Đã gửi CCCD, vui lòng chờ quản trị viên duyệt.':'ID submitted for review.')}else setMessage(result.error??result.message??(vi?'Không thể gửi hồ sơ.':'Could not submit.'))}catch{setMessage(vi?'Không thể gửi hồ sơ.':'Could not submit.')}finally{setBusy(false)}}
const title=status==='approved'?(vi?'CCCD đã được xác thực':'Identity verified'):status==='pending'?(vi?'CCCD đang chờ duyệt':'Identity review pending'):status==='rejected'?(vi?'CCCD bị từ chối':'Identity rejected'):(vi?'Xác thực CCCD':'Verify identity');const showForm=status==='unsubmitted'||status==='rejected';
return <main className="mx-auto w-full max-w-2xl px-4 py-10"><VStack gap={4}><Card variant={status==='approved'?'green':status==='rejected'?'red':'muted'} padding={4}><Heading level={3}>{title}</Heading>{reason?<Text>{vi?'Lý do: ':'Reason: '}{reason}</Text>:null}</Card><Card variant="default" padding={5}><VStack gap={4}><Text type="supporting">{vi?'CCCD đã duyệt cho phép bạn thuê và đặt lịch xem nhà. Quyền này vẫn được giữ khi bạn đăng ký thêm quyền chủ nhà.':'Approved identity allows rentals and viewings and remains valid when owner access is added.'}</Text>{showForm?<form className="flex flex-col gap-4" onSubmit={submit}><label><Text>{vi?'CCCD mặt trước *':'ID front *'}</Text><input className="block w-full rounded-lg border p-2" type="file" name="identity_front" accept="image/jpeg,image/png,application/pdf" required/></label><label><Text>{vi?'CCCD mặt sau *':'ID back *'}</Text><input className="block w-full rounded-lg border p-2" type="file" name="identity_back" accept="image/jpeg,image/png,application/pdf" required/></label><Button type="submit" label={vi?'Gửi CCCD xác thực':'Submit identity'} variant="primary" isLoading={busy}/></form>:null}{message?<Text>{message}</Text>:null}</VStack></Card></VStack></main>}
