'use client';
import {useCallback,useEffect,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {Badge} from '@astryxdesign/core/Badge';import {Button} from '@astryxdesign/core/Button';import {Card} from '@astryxdesign/core/Card';import {Heading} from '@astryxdesign/core/Heading';import {HStack} from '@astryxdesign/core/HStack';import {Text} from '@astryxdesign/core/Text';import {VStack} from '@astryxdesign/core/VStack';import {getCustomerToken} from '../../../../lib/auth';
import {billingUnitLabel,statusLabel} from '../../../../lib/displayLabels';
type Booking={id:number;property_id:number;start_date:string;end_date:string;nights:number;billing_units:number;billing_unit:string;pricing_tier:string;total_price:string;deposit_amount:string;payable_total:string;status:string;property?:{title?:string};owner?:{name?:string;email?:string;phone?:string}};
export default function CustomerBookingsClient(){const {locale='vi'}=useParams<{locale:string}>();const router=useRouter();const[items,setItems]=useState<Booking[]>([]);const[loading,setLoading]=useState(true);const[message,setMessage]=useState('');
 const load=useCallback(async()=>{const token=getCustomerToken();if(!token){router.replace(`/${locale}/customer/login?redirect=/${locale}/customer/bookings`);return}try{const response=await fetch('/api/bookings/mine',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error);setItems(result.data??[])}catch{setMessage('Không thể tải lịch thuê.')}finally{setLoading(false)}},[locale,router]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function action(id:number,name:'cancel'|'complete'){const token=getCustomerToken();if(!token)return;const response=await fetch(`/api/bookings/${id}/${name}`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`}});const result=await response.json();if(!response.ok){setMessage(result.error??'Không thể cập nhật booking.');return}setMessage(name==='complete'?'Đã xác nhận hoàn thành. Bạn có thể đánh giá bất động sản.':'Đã hủy yêu cầu thuê.');await load()}
 return <main className="mx-auto w-full max-w-5xl px-4 py-10"><VStack gap={4}><Heading level={2}>Lịch thuê của tôi</Heading>{message?<Card padding={3}><Text>{message}</Text></Card>:null}{loading?<Text>Đang tải...</Text>:null}{!loading&&!items.length?<Card padding={4}><Text>Bạn chưa có yêu cầu thuê nào.</Text></Card>:null}{items.map(item=><Card key={item.id} padding={4}><VStack gap={2}><HStack justify="between" wrap="wrap"><Heading level={4}>{item.property?.title??'Bất động sản'}</Heading><Badge variant={item.status==='completed'||item.status==='confirmed'?'success':item.status==='pending'?'warning':item.status==='rejected'||item.status==='cancelled'?'error':'info'} label={statusLabel(item.status,locale)}/></HStack><Text><strong>Thời gian:</strong> {item.start_date} → {item.end_date} ({item.nights} đêm)</Text><Text><strong>Kỳ tính tiền:</strong> {item.billing_units} {billingUnitLabel(item.billing_unit,locale)}{item.pricing_tier==='long_term'?' · Giá dài hạn':''}</Text><Text><strong>Tiền thuê:</strong> {Number(item.total_price).toLocaleString('vi-VN')} ₫</Text><Text><strong>Đặt cọc:</strong> {Number(item.deposit_amount).toLocaleString('vi-VN')} ₫</Text><Text><strong>Tổng dự kiến:</strong> {Number(item.payable_total).toLocaleString('vi-VN')} ₫</Text>{item.owner?<Card variant="muted" padding={3}><VStack gap={1}><Text><strong>Liên hệ chủ nhà:</strong> {item.owner.name}</Text><Text>{item.owner.phone||'Chưa có SĐT'} · {item.owner.email}</Text></VStack></Card>:null}<HStack gap={2} wrap="wrap"><Button label="Xem bất động sản" variant="secondary" onClick={()=>router.push(`/${locale}/property/${item.property_id}`)}/>{['pending','confirmed'].includes(item.status)?<Button label="Hủy yêu cầu" variant="secondary" onClick={()=>void action(item.id,'cancel')}/>:null}{item.status==='in_progress'?<Button label="Xác nhận hoàn thành" variant="primary" onClick={()=>void action(item.id,'complete')}/>:null}{item.status==='completed'?<Button label="Đánh giá" variant="primary" onClick={()=>router.push(`/${locale}/property/${item.property_id}#reviews`)}/>:null}</HStack></VStack></Card>)}</VStack></main>}
