'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { getCustomerToken, getCustomerUser } from '../../lib/auth';

type Comment={id:number;body:string;author_name?:string|null;guest_name?:string|null;created_at?:string;replies?:Comment[]};
type Props={slug:string;locale:'vi'|'en';enabled:boolean};

function CommentItem({comment,locale}:{comment:Comment;locale:'vi'|'en'}){return <li className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><strong>{comment.author_name||comment.guest_name||(locale==='vi'?'Ẩn danh':'Anonymous')}</strong>{comment.created_at?<time className="text-xs opacity-60">{new Intl.DateTimeFormat(locale==='vi'?'vi-VN':'en-US',{dateStyle:'medium'}).format(new Date(comment.created_at))}</time>:null}</div><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{comment.body}</p>{comment.replies?.length?<ul className="mt-3 space-y-3 border-l pl-4">{comment.replies.map(reply=><CommentItem key={reply.id} comment={reply} locale={locale}/>)}</ul>:null}</li>}

export default function CommentSection({slug,locale,enabled}:Props){
 const vi=locale==='vi';const[comments,setComments]=useState<Comment[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[user,setUser]=useState<ReturnType<typeof getCustomerUser>>(null);
 const load=useCallback(async()=>{try{const r=await fetch(`/api/blog/${encodeURIComponent(slug)}/comments`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error();setComments(Array.isArray(j.data)?j.data:[])}catch{setMessage(vi?'Không thể tải bình luận.':'Could not load comments.')}finally{setLoading(false)}},[slug,vi]);
 useEffect(()=>{const timer=window.setTimeout(()=>{setUser(getCustomerUser());void load()},0);return()=>window.clearTimeout(timer)},[load]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const form=event.currentTarget;const data=new FormData(form);const token=getCustomerToken();try{const r=await fetch(`/api/blog/${encodeURIComponent(slug)}/comments`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({body:data.get('body'),guest_name:data.get('guest_name')||undefined,guest_email:data.get('guest_email')||undefined})});const j=await r.json();if(!r.ok){const validation=j.errors?Object.values(j.errors).flat().join(' '):'';throw new Error(validation||j.error||j.message)}form.reset();setMessage(vi?'Bình luận đã được gửi và đang chờ duyệt.':'Your comment was submitted and is awaiting approval.');await load()}catch(error){setMessage(error instanceof Error&&error.message?error.message:(vi?'Không thể gửi bình luận.':'Could not submit comment.'))}finally{setBusy(false)}}
 return <section className="mt-10 border-t pt-8" aria-labelledby="comments-heading"><h2 id="comments-heading" className="text-2xl font-bold">{vi?'Bình luận':'Comments'}</h2>{enabled?<form onSubmit={submit} className="mt-5 grid gap-3 rounded-2xl border p-4">{!user?<div className="grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-sm"><span>{vi?'Tên của bạn':'Your name'}</span><input required name="guest_name" maxLength={120} className="rounded-xl border bg-transparent px-3 py-2"/></label><label className="grid gap-1 text-sm"><span>Email</span><input required type="email" name="guest_email" className="rounded-xl border bg-transparent px-3 py-2"/></label></div>:<p className="text-sm opacity-75">{vi?`Bình luận với tên ${user.name}`:`Commenting as ${user.name}`}</p>}<label className="grid gap-1 text-sm"><span>{vi?'Nội dung bình luận':'Comment'}</span><textarea required minLength={3} maxLength={5000} name="body" rows={4} className="rounded-xl border bg-transparent px-3 py-2"/></label><button disabled={busy} className="w-fit rounded-xl bg-zinc-900 px-5 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy?(vi?'Đang gửi...':'Submitting...'):(vi?'Gửi bình luận':'Submit comment')}</button></form>:<p className="mt-3 text-sm opacity-70">{vi?'Bài viết này đã tắt bình luận.':'Comments are disabled for this article.'}</p>}{message?<p className="mt-3 rounded-xl border px-4 py-3 text-sm" role="status">{message}</p>:null}{loading?<p className="mt-5 text-sm opacity-70">{vi?'Đang tải bình luận...':'Loading comments...'}</p>:comments.length?<ul className="mt-5 space-y-3">{comments.map(comment=><CommentItem key={comment.id} comment={comment} locale={locale}/>)}</ul>:<p className="mt-5 text-sm opacity-70">{vi?'Chưa có bình luận được duyệt.':'No approved comments yet.'}</p>}</section>;
}
