import { useCallback, useEffect, useRef, useState } from 'react';
import { Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, Grid, Stack, TextField, Typography } from '@mui/material';
import { useNavigate, useParams } from 'react-router-dom';
import MainCard from '@components/MainCard';
import { useGlobalContext } from '@providers/GlobalProvider';
import { getOwnerApplication, getOwnerDocument, reviewOwnerApplication, setTestPostingCredits } from './OwnerApplicationServices';

const statusColor = { pending: 'warning', approved: 'success', rejected: 'error' };
const statusLabel = { pending: 'Chờ duyệt', approved: 'Đã duyệt', rejected: 'Từ chối' };

export default function OwnerApplicationDetail() {
    const { id } = useParams(); const navigate = useNavigate(); const ui = useGlobalContext(); const uiRef = useRef(ui); uiRef.current = ui;
    const [item,setItem]=useState(null); const [reason,setReason]=useState(''); const [preview,setPreview]=useState(null); const [zoom,setZoom]=useState(1); const [testCredits,setTestCredits]=useState(0);
    const loadData=useCallback(async()=>{uiRef.current.showLoading();try{const response=await getOwnerApplication(id);const data=response.data?.data??null;setItem(data);setTestCredits(data?.user?.test_posting_credits??0)}catch(error){uiRef.current.showNotification(error.response?.data?.error||'Không thể tải hồ sơ','error');navigate('/dashboard/owner-applications')}finally{uiRef.current.hideLoading()}},[id,navigate]);
    useEffect(()=>{void loadData()},[loadData]);
    useEffect(()=>()=>{if(preview?.url)URL.revokeObjectURL(preview.url)},[preview]);

    async function openDocument(type){try{const response=await getOwnerDocument(id,type);const url=URL.createObjectURL(response.data);const titles={'identity-front':'CCCD mặt trước','identity-back':'CCCD mặt sau',ownership:'Giấy tờ chứng minh sở hữu'};setZoom(1);setPreview({url,contentType:response.headers?.['content-type']||response.data?.type||'',title:titles[type]})}catch(error){uiRef.current.showNotification(error.response?.data?.error||'Không thể mở giấy tờ','error')}}
    function closePreview(){if(preview?.url)URL.revokeObjectURL(preview.url);setPreview(null)}
    async function review(status){if(status==='rejected'&&!reason.trim()){uiRef.current.showNotification('Vui lòng nhập lý do từ chối','warning');return}uiRef.current.showLoading();try{await reviewOwnerApplication(id,{status,rejection_reason:status==='rejected'?reason.trim():null});uiRef.current.showNotification(status==='approved'?'Đã duyệt hồ sơ':'Đã từ chối hồ sơ','success');await loadData()}catch(error){uiRef.current.showNotification(error.response?.data?.error||error.response?.data?.message||'Không thể cập nhật','error')}finally{uiRef.current.hideLoading()}}
    async function saveTestCredits(){uiRef.current.showLoading();try{await setTestPostingCredits(id,Number(testCredits));uiRef.current.showNotification('Đã cập nhật lượt đăng tin kiểm thử','success');await loadData()}catch(error){uiRef.current.showNotification(error.response?.data?.error||error.response?.data?.message||'Không thể cập nhật lượt đăng tin','error')}finally{uiRef.current.hideLoading()}}

    if(!item)return null;
    return <MainCard title={`Chi tiết hồ sơ #${item.id}`}>
        <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2} sx={{mb:3}}><Button onClick={()=>navigate('/dashboard/owner-applications')}>← Quay lại danh sách</Button><Chip color={statusColor[item.status]||'default'} label={statusLabel[item.status]||item.status}/></Stack>
        <Grid container spacing={3}><Grid item xs={12} md={6}><Card variant="outlined"><CardContent><Typography variant="h6" gutterBottom>Thông tin người đăng ký</Typography><Stack spacing={1}><Typography><b>Họ tên:</b> {item.user?.name}</Typography><Typography><b>Email:</b> {item.user?.email}</Typography><Typography><b>Điện thoại:</b> {item.user?.detail?.phone||'—'}</Typography><Typography><b>Địa chỉ:</b> {[item.user?.detail?.address,item.user?.detail?.city].filter(Boolean).join(', ')||'—'}</Typography><Typography><b>Ngày gửi:</b> {new Date(item.created_at).toLocaleString('vi-VN')}</Typography>{item.note?<Typography><b>Ghi chú:</b> {item.note}</Typography>:null}</Stack></CardContent></Card></Grid>
        <Grid item xs={12} md={6}><Card variant="outlined"><CardContent><Typography variant="h6" gutterBottom>Giấy tờ xác minh</Typography><Stack spacing={1}><Button variant="outlined" onClick={()=>void openDocument('identity-front')}>Xem CCCD mặt trước</Button>{item.identity_back_path?<Button variant="outlined" onClick={()=>void openDocument('identity-back')}>Xem CCCD mặt sau</Button>:null}<Button variant="outlined" onClick={()=>void openDocument('ownership')}>Xem giấy tờ sở hữu</Button></Stack></CardContent></Card></Grid></Grid>
        <Divider sx={{my:3}}/>{item.status==='approved'?<Card variant="outlined" sx={{mb:3}}><CardContent><Typography variant="h6" gutterBottom>Lượt đăng tin kiểm thử</Typography><Typography color="text.secondary" sx={{mb:2}}>Hệ thống trừ lượt này trước, không trừ tiền ví. Đặt bằng 0 để tắt quyền đăng miễn phí.</Typography><Stack direction={{xs:'column',sm:'row'}} spacing={2} alignItems={{sm:'center'}}><TextField type="number" label="Số lượt còn lại" value={testCredits} onChange={(event)=>setTestCredits(Math.max(0,Math.min(1000,Number(event.target.value)||0)))} inputProps={{min:0,max:1000}}/><Button variant="contained" onClick={()=>void saveTestCredits()}>Lưu số lượt</Button></Stack></CardContent></Card>:null}{item.rejection_reason?<Typography color="error" sx={{mb:2}}><b>Lý do từ chối:</b> {item.rejection_reason}</Typography>:null}{item.status==='pending'?<Stack spacing={2}><TextField label="Lý do từ chối" multiline minRows={3} value={reason} onChange={(event)=>setReason(event.target.value)}/><Stack direction="row" spacing={2}><Button variant="contained" color="success" onClick={()=>void review('approved')}>Duyệt hồ sơ</Button><Button variant="outlined" color="error" onClick={()=>void review('rejected')}>Từ chối</Button></Stack></Stack>:null}
        <Dialog open={Boolean(preview)} onClose={closePreview} fullWidth maxWidth="lg"><DialogTitle>{preview?.title}</DialogTitle>{preview?.contentType?.startsWith('image/')?<Stack direction="row" justifyContent="center" alignItems="center" spacing={1} sx={{px:3,pb:1}}><Button size="small" variant="outlined" disabled={zoom<=.25} onClick={()=>setZoom(value=>Math.max(.25,value-.25))}>− Thu nhỏ</Button><Typography sx={{minWidth:56,textAlign:'center',fontWeight:600}}>{Math.round(zoom*100)}%</Typography><Button size="small" variant="outlined" disabled={zoom>=3} onClick={()=>setZoom(value=>Math.min(3,value+.25))}>+ Phóng to</Button><Button size="small" onClick={()=>setZoom(1)}>Đặt lại</Button></Stack>:null}<DialogContent dividers sx={{minHeight:{xs:420,md:650},overflow:'auto',bgcolor:'grey.100'}}>{preview?.contentType?.startsWith('image/')?<Box sx={{minWidth:'100%',minHeight:{xs:380,md:610},display:'flex',alignItems:'center',justifyContent:'center',p:2}}><Box component="img" src={preview.url} alt={preview.title} sx={{display:'block',maxWidth:zoom<=1?'100%':'none',maxHeight:zoom<=1?'70vh':'none',transform:`scale(${zoom})`,transformOrigin:'center',transition:'transform 150ms ease'}}/></Box>:null}{preview?.contentType==='application/pdf'?<Box component="iframe" src={preview.url} title={preview.title} sx={{width:'100%',height:'75vh',border:0,bgcolor:'white'}}/>:null}</DialogContent><DialogActions><Button onClick={()=>preview?.url&&window.open(preview.url,'_blank','noopener,noreferrer')}>Mở tab mới</Button><Button variant="contained" onClick={closePreview}>Đóng</Button></DialogActions></Dialog>
    </MainCard>;
}
