'use client';
import {useCallback,useEffect,useRef,useState} from 'react';import {usePathname,useRouter,useSearchParams} from 'next/navigation';import {Button} from '@astryxdesign/core/Button';import {Card} from '@astryxdesign/core/Card';import {Text} from '@astryxdesign/core/Text';import {VStack} from '@astryxdesign/core/VStack';import type {Locale} from '../../i18n/config';import {getMessages} from '../../i18n/messages';import PropertyCard,{type PropertyCardItem} from './PropertyCard';import PropertyListSkeleton from './PropertyListSkeleton';
type Response={data?:PropertyCardItem[];meta?:{current_page?:number;total?:number}};
export default function PropertyInfiniteList({locale,initialProperties,initialCurrentPage,initialTotal}:{locale:Locale;initialProperties:PropertyCardItem[];initialCurrentPage:number;initialTotal:number}){const messages=getMessages(locale);const router=useRouter();const pathname=usePathname();const searchParams=useSearchParams();const[properties,setProperties]=useState(initialProperties);const[currentPage,setCurrentPage]=useState(initialCurrentPage);const[total,setTotal]=useState(initialTotal);const[exhausted,setExhausted]=useState(initialProperties.length>=initialTotal);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const sentinel=useRef<HTMLDivElement>(null);const hasMore=!exhausted&&properties.length<total;
useEffect(()=>{const saved=sessionStorage.getItem('homelend:scrollY');if(saved){const position=Number(saved);if(Number.isFinite(position))window.scrollTo({top:position,behavior:'auto'});sessionStorage.removeItem('homelend:scrollY')}},[]);
useEffect(()=>{const params=new URLSearchParams(searchParams.toString());if(params.get('page')!==String(currentPage)){params.set('page',String(currentPage));router.replace(`${pathname}?${params}`,{scroll:false})}},[currentPage,pathname,router,searchParams]);
const loadMore=useCallback(async()=>{if(loading||!hasMore)return;setLoading(true);setError('');const nextPage=currentPage+1;const params=new URLSearchParams(searchParams.toString());params.set('page',String(nextPage));try{const response=await fetch(`/api/properties?${params}`,{cache:'no-store'});if(!response.ok)throw new Error(messages.loadErrorDetail);const payload:Response=await response.json();const incoming=payload.data??[];const responseTotal=payload.meta?.total;if(!incoming.length)setExhausted(true);setProperties(previous=>{const ids=new Set(previous.map(item=>item.id));const combined=[...previous,...incoming.filter(item=>!ids.has(item.id))];if(typeof responseTotal==='number'&&combined.length>=responseTotal)setExhausted(true);return combined});setCurrentPage(payload.meta?.current_page??nextPage);if(typeof responseTotal==='number')setTotal(responseTotal)}catch(reason){setError(reason instanceof Error?reason.message:messages.loadErrorDetail)}finally{setLoading(false)}},[currentPage,hasMore,loading,messages.loadErrorDetail,searchParams]);
useEffect(()=>{const target=sentinel.current;if(!hasMore||!target)return;const observer=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting)void loadMore()},{rootMargin:'300px 0px'});observer.observe(target);return()=>observer.disconnect()},[hasMore,loadMore]);
return <><section aria-label={messages.listAriaLabel} className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{properties.map(property=><PropertyCard key={property.id} property={property} locale={locale}/>)}</section>{!properties.length?<Card variant="muted" padding={4}><Text>{messages.emptyState}</Text></Card>:null}{error?<Card variant="orange" padding={3}><VStack gap={2}><Text>{error}</Text><Button label={messages.retryLoadMore} variant="secondary" onClick={()=>void loadMore()}/></VStack></Card>:null}{!hasMore&&properties.length?<Card variant="muted" padding={3}><Text>{messages.allLoaded}</Text></Card>:null}{loading?<PropertyListSkeleton/>:null}<div ref={sentinel} className="h-1 w-full" aria-hidden="true"/></>}
